mysql:
  host: ${API_SERVER_MYSQL_HOST} # MySQL 机器 ip 和端口，默认 127.0.0.1:3306
  username: ${API_SERVER_MYSQL_USERNAME} # MySQL 用户名(建议授权最小权限集)
  password: ${API_SERVER_MYSQL_PASSWORD} # MySQL 用户密码
  database: ${API_SERVER_MYSQL_DATABASE} # iam 系统所用的数据库名
  max-idle-connections: 100 # MySQL 最大空闲连接数，默认 100
  max-open-connections: 100 # MySQL 最大打开的连接数，默认 100
  max-connection-life-time: 10s # 空闲连接最大存活时间，默认 10s
  log-level: 4 # GORM log level, 1: silent, 2:error, 3:warn, 4:info